2018-11-26 15:06:47,133 | ERROR | framedata-bot.client | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 55, in on_message
    await self._handle(message)
  File "bot/client.py", line 71, in _handle
    output, send_dm = self.data.respond(msg_obj, args, options)
  File "bot/searchableTree.py", line 39, in respond
    return super().respond(msg_obj, args, options)
  File "bot/response.py", line 28, in respond
    return self._handleArgs(self, args, options)
  File "bot/searchableTree.py", line 29, in _handleArgs
    return self._match(msg_obj, args, options)
TypeError: _match() missing 1 required positional argument: 'send_dm'
2018-11-26 15:06:49,397 | ERROR | framedata-bot.client | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 55, in on_message
    await self._handle(message)
  File "bot/client.py", line 71, in _handle
    output, send_dm = self.data.respond(msg_obj, args, options)
  File "bot/searchableTree.py", line 39, in respond
    return super().respond(msg_obj, args, options)
  File "bot/response.py", line 28, in respond
    return self._handleArgs(self, args, options)
  File "bot/searchableTree.py", line 29, in _handleArgs
    return self._match(msg_obj, args, options)
TypeError: _match() missing 1 required positional argument: 'send_dm'
2018-11-26 15:10:00,407 | ERROR | framedata-bot.client | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 55, in on_message
    await self._handle(message)
  File "bot/client.py", line 71, in _handle
    output, send_dm = self.data.respond(msg_obj, args, options)
  File "bot/searchableTree.py", line 32, in respond
    send_dm = self._checkOptions(options)
  File "bot/response.py", line 41, in _checkOptions
    return self._send_dm_default
AttributeError: 'AllStructuredData' object has no attribute '_send_dm_default'
2018-11-26 15:16:19,818 | ERROR | framedata-bot.client | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 55, in on_message
    await self._handle(message)
  File "bot/client.py", line 71, in _handle
    output, send_dm = self.data.respond(msg_obj, args, options)
  File "bot/searchableTree.py", line 39, in respond
    return super().respond(msg_obj, args, options)
  File "bot/response.py", line 30, in respond
    return self._handleArgs(self, args, send_dm, options)
  File "bot/searchableTree.py", line 29, in _handleArgs
    return self._match(msg_obj, send_dm, args, options)
  File "bot/searchableTree.py", line 47, in _match
    guess, *extra_args = args
TypeError: cannot unpack non-iterable bool object
2018-11-26 15:17:48,144 | ERROR | framedata-bot.client | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 55, in on_message
    await self._handle(message)
  File "bot/client.py", line 74, in _handle
    logger.info(f'Command Handled | msg_obj: {msg_obj},'
AttributeError: 'Client' object has no attribute 'output'
2018-11-26 15:17:54,790 | ERROR | framedata-bot.client | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 55, in on_message
    await self._handle(message)
  File "bot/client.py", line 74, in _handle
    logger.info(f'Command Handled | msg_obj: {msg_obj},'
AttributeError: 'Client' object has no attribute 'output'
2018-11-26 15:17:57,834 | ERROR | framedata-bot.client | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 55, in on_message
    await self._handle(message)
  File "bot/client.py", line 74, in _handle
    logger.info(f'Command Handled | msg_obj: {msg_obj},'
AttributeError: 'Client' object has no attribute 'output'
2018-11-26 15:18:07,063 | ERROR | framedata-bot.client | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 55, in on_message
    await self._handle(message)
  File "bot/client.py", line 74, in _handle
    logger.info(f'Command Handled | msg_obj: {msg_obj},'
AttributeError: 'Client' object has no attribute 'output'
2018-11-26 15:18:19,916 | ERROR | framedata-bot.client | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 55, in on_message
    await self._handle(message)
  File "bot/client.py", line 74, in _handle
    logger.info(f'Command Handled | msg_obj: {msg_obj},'
AttributeError: 'Client' object has no attribute 'output'
2018-11-26 15:20:46,154 | ERROR | framedata-bot.client | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 55, in on_message
    await self._handle(message)
  File "bot/client.py", line 74, in _handle
    logger.info(f'Command Handled | msg_obj: {msg_obj},'
AttributeError: 'Client' object has no attribute 'output'
2018-11-26 15:20:52,876 | ERROR | framedata-bot.client | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 55, in on_message
    await self._handle(message)
  File "bot/client.py", line 74, in _handle
    logger.info(f'Command Handled | msg_obj: {msg_obj},'
AttributeError: 'Client' object has no attribute 'output'
2018-11-26 15:21:35,409 | ERROR | framedata-bot.client | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 55, in on_message
    await self._handle(message)
  File "bot/client.py", line 74, in _handle
    logger.info(f'Command Handled | msg_obj: {msg_obj},'
AttributeError: 'Client' object has no attribute 'output'
2018-11-29 10:56:35,205 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 53, in on_message
    if not self._isCommand(message):
AttributeError: 'Client' object has no attribute '_isCommand'
2018-11-29 10:57:20,510 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 75, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 89, in __init__
    args, options = self._parse(msg_obj.content)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 112, in _parse
    words = content[len(self.conf.command_prefix):].split()
AttributeError: 'Handler' object has no attribute 'conf'
2018-11-29 11:00:27,169 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 92, in __init__
    response = self.searchable_tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 80, in respond
    return self._handleArgs(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 76, in _handleArgs
    return self._match(msg_obj, args, options)
TypeError: _match() missing 1 required positional argument: 'options'
2018-11-29 11:31:06,367 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 92, in __init__
    response = self.searchable_tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 80, in respond
    return self._handleArgs(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 76, in _handleArgs
    return self._match(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 106, in _match
    options = self._children.keys() + self.aliases.keys()
AttributeError: 'SearchableTreeNode' object has no attribute 'aliases'
2018-11-29 11:35:27,347 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 92, in __init__
    response = self.searchable_tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 80, in respond
    return self._handleArgs(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 76, in _handleArgs
    return self._match(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 106, in _match
    options = self._children.keys() + self._aliases.keys()
AttributeError: 'list' object has no attribute 'keys'
2018-11-29 11:45:50,501 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 92, in __init__
    response = self.searchable_tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 86, in respond
    return self._handleArgs(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 82, in _handleArgs
    return self._match(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 112, in _match
    options = self._children.keys() + self._child_aliases.keys()
TypeError: unsupported operand type(s) for +: 'dict_keys' and 'dict_keys'
2018-11-29 11:48:36,070 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 92, in __init__
    response = self.searchable_tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 86, in respond
    return self._handleArgs(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 82, in _handleArgs
    return self._match(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 114, in _match
    if match in self._child_aliases.keys():
TypeError: unhashable type: 'dict_keys'
2018-11-29 11:57:35,146 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 92, in __init__
    response = self.searchable_tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 86, in respond
    return self._handleArgs(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 82, in _handleArgs
    return self._match(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 116, in _match
    if match in self._child_aliases.keys():
TypeError: unhashable type: 'list'
2018-11-29 12:00:32,223 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 92, in __init__
    response = self.searchable_tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 86, in respond
    return self._handleArgs(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 82, in _handleArgs
    return self._match(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 116, in _match
    if match in self._child_aliases.keys():
TypeError: unhashable type: 'dict_keys'
2018-11-29 12:03:33,774 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 94, in __init__
    self._output, self._behavior_output = response
ValueError: not enough values to unpack (expected 2, got 1)
2018-11-29 12:03:54,039 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 77, in _handle
    await handler.respond()
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 98, in respond
    channel = await self._handleBehaviorOutput(self._behavior_output)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 126, in _handleBehaviorOutput
    if 'dm' in b_o:
TypeError: argument of type 'bool' is not iterable
2018-11-29 12:03:57,184 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 77, in _handle
    await handler.respond()
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 98, in respond
    channel = await self._handleBehaviorOutput(self._behavior_output)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 126, in _handleBehaviorOutput
    if 'dm' in b_o:
TypeError: argument of type 'bool' is not iterable
2018-11-29 12:09:00,997 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 77, in _handle
    await handler.respond()
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 98, in respond
    channel = await self._handleBehaviorOutput(self._behavior_output)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 126, in _handleBehaviorOutput
    if 'dm' in b_o:
TypeError: argument of type 'bool' is not iterable
2018-11-29 12:09:55,671 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 77, in _handle
    await handler.respond()
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 98, in respond
    channel = await self._handleBehaviorOutput(self._behavior_output)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 126, in _handleBehaviorOutput
    if 'dm' in b_o:
TypeError: argument of type 'bool' is not iterable
2018-11-29 12:12:27,925 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 77, in _handle
    await handler.respond()
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 98, in respond
    channel = await self._handleBehaviorOutput(self._behavior_output)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 126, in _handleBehaviorOutput
    if 'dm' in b_o:
TypeError: argument of type 'bool' is not iterable
2018-11-29 12:23:14,061 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 93, in __init__
    self._output, self._behavior_output = response
ValueError: not enough values to unpack (expected 2, got 1)
2018-11-29 12:26:21,247 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 93, in __init__
    self._output, self._behavior_output = response
ValueError: not enough values to unpack (expected 2, got 1)
2018-11-29 12:28:15,633 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 93, in __init__
    self._output, self._behavior_output = response
ValueError: not enough values to unpack (expected 2, got 1)
2018-11-29 21:30:32,365 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 92, in __init__
    response = self.searchable_tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 87, in respond
    return self._handleArgs(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 82, in _handleArgs
    return self._match(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 124, in _match
    return matched_child.respond(msg_obj, extra_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 86, in respond
    if user_args:
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 103, in _checkBehaviors
    behavior_output.append(behavior.execute(checked_options))
AttributeError: 'set' object has no attribute 'append'
2018-11-29 21:31:25,004 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 77, in _handle
    await handler.respond()
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 97, in respond
    channel = await self._handleBehaviorOutput(self._behavior_output)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 127, in _handleBehaviorOutput
    channel = await self._getDMChannel()
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 147, in _getDMChannel
    if not author.dm_channel:
NameError: name 'author' is not defined
2018-11-29 21:32:34,811 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 77, in _handle
    await handler.respond()
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 97, in respond
    channel = await self._handleBehaviorOutput(self._behavior_output)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 127, in _handleBehaviorOutput
    channel = await self._getDMChannel()
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 149, in _getDMChannel
    logger.info(f'new dm channel for {self.msg_obj.author}')
AttributeError: 'Handler' object has no attribute 'msg_obj'
2018-11-29 21:33:13,703 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 77, in _handle
    await handler.respond()
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 97, in respond
    channel = await self._handleBehaviorOutput(self._behavior_output)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 130, in _handleBehaviorOutput
    await self._send(self.msg_obj.channel, dm_notify)
AttributeError: 'Handler' object has no attribute 'msg_obj'
2018-12-01 10:43:00,717 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 92, in __init__
    response = self.searchable_tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 89, in respond
    return self._handleArgs(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 100, in _handleArgs
    return self._match(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 124, in _match
    return matched_child.respond(msg_obj, extra_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 96, in respond
    behaviour_output = self._checkBehaviours(options)
AttributeError: 'SearchableTreeNode' object has no attribute '_checkBehaviours'
2018-12-01 10:43:18,800 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 92, in __init__
    response = self.searchable_tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 89, in respond
    return self._handleArgs(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 100, in _handleArgs
    return self._match(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 124, in _match
    return matched_child.respond(msg_obj, extra_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 96, in respond
    behaviour_output = self._checkBehaviours(options)
AttributeError: 'SearchableTreeNode' object has no attribute '_checkBehaviours'
2018-12-01 11:49:37,720 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 56, in on_message
    await self._handle(message)
  File "bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "bot/client.py", line 92, in __init__
    response = self.searchable_tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 89, in respond
    return self._handleArgs(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 100, in _handleArgs
    return self._match(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 124, in _match
    return matched_child.respond(msg_obj, extra_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 96, in respond
    behaviour_output = self._checkBehaviours(options)
AttributeError: 'SearchableTreeNode' object has no attribute '_checkBehaviours'
2018-12-01 11:50:38,368 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 56, in on_message
    await self._handle(message)
  File "bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "bot/client.py", line 92, in __init__
    response = self.searchable_tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 89, in respond
    return self._handleArgs(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 100, in _handleArgs
    return self._match(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 124, in _match
    return matched_child.respond(msg_obj, extra_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/searchableTree.py", line 96, in respond
    behaviour_output = self._checkBehaviours(options)
AttributeError: 'SearchableTreeNode' object has no attribute '_checkBehaviours'
2018-12-01 11:51:08,809 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot/client.py", line 56, in on_message
    await self._handle(message)
  File "bot/client.py", line 77, in _handle
    await handler.respond()
  File "bot/client.py", line 97, in respond
    channel = await self._handleBehaviorOutput(self._behavior_output)
  File "bot/client.py", line 125, in _handleBehaviorOutput
    if 'dm' in b_o:
TypeError: argument of type 'NoneType' is not iterable
2018-12-02 08:35:57,596 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 84, in respond
    return self._handleArgs(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 92, in _handleArgs
    options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 111, in _matchChild
    match, rate = process.extractOne(guess, self._valid_matches)
AttributeError: 'Root' object has no attribute '_valid_matches'
2018-12-02 09:49:34,089 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 88, in respond
    return self._handleArgs(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 96, in _handleArgs
    options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 115, in _matchChild
    match, rate = process.extractOne(guess, self._valid_matches)
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/fuzzywuzzy/process.py", line 220, in extractOne
    return max(best_list, key=lambda i: i[1])
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/fuzzywuzzy/process.py", line 78, in extractWithoutOrder
    processed_query = processor(query)
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/fuzzywuzzy/utils.py", line 95, in full_process
    string_out = StringProcessor.replace_non_letters_non_numbers_with_whitespace(s)
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/fuzzywuzzy/string_processing.py", line 26, in replace_non_letters_non_numbers_with_whitespace
    return cls.regex.sub(" ", a_string)
TypeError: expected string or bytes-like object
2018-12-02 11:40:21,141 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 88, in respond
    return self._handleArgs(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 96, in _handleArgs
    options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 115, in _matchChild
    match, rate = process.extractOne(guess, self._valid_matches)
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/fuzzywuzzy/process.py", line 220, in extractOne
    return max(best_list, key=lambda i: i[1])
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/fuzzywuzzy/process.py", line 78, in extractWithoutOrder
    processed_query = processor(query)
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/fuzzywuzzy/utils.py", line 95, in full_process
    string_out = StringProcessor.replace_non_letters_non_numbers_with_whitespace(s)
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/fuzzywuzzy/string_processing.py", line 26, in replace_non_letters_non_numbers_with_whitespace
    return cls.regex.sub(" ", a_string)
TypeError: expected string or bytes-like object
2018-12-02 11:41:35,479 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 88, in respond
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 100, in _handleArgs
    if is_aliased:
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 90, in respond
    guess, *user_args = user_args
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 145, in _handleNoArgs
    class Root(UserFacingNode):
AttributeError: 'list' object has no attribute 'format'
2018-12-02 11:44:08,320 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 93, in __init__
    self._output, self._behavior_output = response
TypeError: cannot unpack non-iterable WrittenMSG object
2018-12-02 11:51:44,658 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.respond()
  File "client.py", line 97, in respond
    channel = await self._getDMChannel(self._channel_key)
TypeError: _getDMChannel() takes 1 positional argument but 2 were given
2018-12-02 11:53:21,250 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 93, in __init__
    self._output, self._channel_key = response
TypeError: cannot unpack non-iterable WrittenMSG object
2018-12-02 11:58:49,075 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 93, in __init__
    self._output, self._channel_key = response
TypeError: cannot unpack non-iterable WrittenMSG object
2018-12-02 12:00:19,846 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 135, in _send
    for out in output:
TypeError: 'WrittenMSG' object is not iterable
2018-12-02 12:00:41,491 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 136, in _send
    await channel.send(**out)
TypeError: send() argument after ** must be a mapping, not WrittenMSG
2018-12-02 12:02:04,256 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 136, in _send
    await channel.send(**out)
TypeError: send() argument after ** must be a mapping, not list
2018-12-02 12:03:04,697 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 136, in _send
    await channel.send(**out)
TypeError: send() argument after ** must be a mapping, not list
2018-12-02 12:05:58,167 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 136, in _send
    await channel.send(**out)
TypeError: send() argument after ** must be a mapping, not tuple
2018-12-02 12:08:48,258 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 136, in _send
    await channel.send(**out)
TypeError: send() argument after ** must be a mapping, not tuple
2018-12-02 12:09:02,687 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 136, in _send
    await channel.send(**out)
TypeError: send() argument after ** must be a mapping, not list
2018-12-02 12:11:30,720 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 138, in _send
    await channel.send(**out)
TypeError: send() argument after ** must be a mapping, not list
2018-12-02 12:11:53,509 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 138, in _send
    await channel.send(**out)
TypeError: send() argument after ** must be a mapping, not list
2018-12-02 13:39:59,848 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 138, in _send
    await channel.send(**out)
AttributeError: 'NoneType' object has no attribute 'send'
2018-12-02 13:43:08,794 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 97, in query
    channel = await self._getChannel(self._behaviors.send_dm)
AttributeError: 'dict' object has no attribute 'send_dm'
2018-12-02 14:39:17,868 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 102, in _handleArgs
    return matched_child.respond(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 90, in respond
    return response, self._default_behaviours
AttributeError: 'LongOutput' object has no attribute '_default_behaviours'
2018-12-02 14:39:26,447 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 102, in _handleArgs
    return matched_child.respond(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 90, in respond
    return response, self._default_behaviours
AttributeError: 'LongOutput' object has no attribute '_default_behaviours'
2018-12-02 14:50:26,171 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 101, in query
    await self._send(channel, self._output)
  File "client.py", line 139, in _send
    await channel.send(**out)
AttributeError: 'NoneType' object has no attribute 'send'
2018-12-02 14:54:18,386 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 101, in query
    await self._send(channel, self._output)
  File "client.py", line 139, in _send
    await channel.send(**out)
AttributeError: 'NoneType' object has no attribute 'send'
2018-12-02 14:56:25,584 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 134, in _send
    if not output:
AttributeError: 'NoneType' object has no attribute 'send'
2018-12-02 14:58:37,578 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 138, in _send
    await channel.send(**out)
AttributeError: 'NoneType' object has no attribute 'send'
2018-12-02 15:02:17,223 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 134, in _send
    if not output:
AttributeError: 'NoneType' object has no attribute 'send'
2018-12-02 15:03:06,695 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 138, in _send
    await channel.send(**out)
AttributeError: 'NoneType' object has no attribute 'send'
2018-12-02 15:03:22,110 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 138, in _send
    await channel.send(**out)
AttributeError: 'NoneType' object has no attribute 'send'
2018-12-02 15:03:27,610 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    await self._send(channel, self._output)
  File "client.py", line 138, in _send
    await channel.send(**out)
AttributeError: 'NoneType' object has no attribute 'send'
2018-12-02 22:00:49,966 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 90, in respond
    return response, self._default_behaviours
AttributeError: 'Root' object has no attribute '_default_behaviours'
2018-12-02 22:13:49,121 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 102, in _handleArgs
    return matched_child.respond(msg_obj, user_args, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 83, in respond
    response = self._handleNoArgs(msg_obj, options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 133, in _handleNoArgs
    behaviours = self._checkBehaviors(options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 152, in _checkBehaviors
    return Behaviours(send_dm=False, load=False)
TypeError: __new__() got an unexpected keyword argument 'load'
2018-12-02 22:15:20,686 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 77, in _handle
    await handler.query()
  File "client.py", line 100, in query
    self._tree = userFacingTree.load()
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 173, in load
    root_node = json.loads(f.read())
  File "/usr/lib64/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 63 column 21 (char 4669)
2018-12-03 22:27:42,620 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options)
TypeError: respond() takes 3 positional arguments but 4 were given
2018-12-03 22:29:44,518 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 103, in _handleArgs
    options)
TypeError: _matchChild() takes 3 positional arguments but 4 were given
2018-12-03 22:30:52,753 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 107, in _handleArgs
    return matched_child.respond(msg_obj, user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 84, in respond
    return self._package(response)
AttributeError: 'UserFacingNode' object has no attribute '_package'
2018-12-03 22:36:51,449 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 68, in on_message_edit
    await self._handle(after)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 107, in _handleArgs
    return matched_child.respond(msg_obj, user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 167, in respond
    target, suggestion = self._parseSuggestion
TypeError: cannot unpack non-iterable method object
2018-12-03 22:38:01,992 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 107, in _handleArgs
    return matched_child.respond(msg_obj, user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 167, in respond
    target, suggestion = self._parseSuggestion(user_args)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 177, in _parseSuggestion
    raise ValueError('ur value is shit m8')
ValueError: ur value is shit m8
2018-12-03 22:38:29,594 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 68, in on_message_edit
    await self._handle(after)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 107, in _handleArgs
    return matched_child.respond(msg_obj, user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 171, in respond
    suggestion=suggestion)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 101, in _handleArgs
    guess)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 123, in _matchChild
    match, rate = process.extractOne(guess, self._valid_matches)
AttributeError: 'Suggest' object has no attribute '_valid_matches'
2018-12-03 22:41:37,723 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 107, in _handleArgs
    return matched_child.respond(msg_obj, user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 174, in respond
    suggestion=suggestion)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 103, in _handleArgs
    if rate < self.conf.min_match_percent:
AttributeError: type object 'Suggest' has no attribute 'min_match_percent'
2018-12-04 08:40:42,369 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 107, in _handleArgs
    return matched_child.respond(msg_obj, user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 174, in respond
    suggestion=suggestion)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 107, in _handleArgs
    return matched_child.respond(msg_obj, user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 174, in respond
    suggestion=suggestion)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 107, in _handleArgs
    return matched_child.respond(msg_obj, user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 174, in respond
    suggestion=suggestion)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 83, in respond
    response = self._handleNoArgs(msg_obj, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 187, in _handleNoArgs
    self._queueSuggestion(suggestion)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 191, in _queueSuggestion
    with open(self.conf.suggestion_que_loc, '+') as f:
ValueError: Must have exactly one of create/read/write/append mode and at most one plus
2018-12-04 08:45:08,900 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "client.py", line 56, in on_message
    await self._handle(message)
  File "client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 107, in _handleArgs
    return matched_child.respond(msg_obj, user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 174, in respond
    suggestion=suggestion)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 107, in _handleArgs
    return matched_child.respond(msg_obj, user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 174, in respond
    suggestion=suggestion)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 81, in respond
    **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 107, in _handleArgs
    return matched_child.respond(msg_obj, user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 174, in respond
    suggestion=suggestion)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 83, in respond
    response = self._handleNoArgs(msg_obj, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 187, in _handleNoArgs
    self._queueSuggestion(suggestion)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/userFacingTree.py", line 191, in _queueSuggestion
    with open(self.conf.suggestion_que_loc, 'w+r') as f:
ValueError: must have exactly one of create/read/write/append mode
2018-12-19 20:14:24,440 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 92, in __init__
    response = self._tree.respond(msg_obj, args, options=options)
TypeError: respond() takes 2 positional arguments but 3 were given
2018-12-19 20:17:29,003 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 93, in __init__
    options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/nodeStrategies.py", line 151, in respond
    response = self._handleArgs(user_args, **kwargs)
TypeError: handleArgs() got multiple values for argument 'msg_obj'
2018-12-19 20:19:17,096 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 93, in __init__
    options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/nodeStrategies.py", line 152, in respond
    response = self._handleArgs(user_args, **kwargs)
TypeError: handleArgs() got multiple values for argument 'msg_obj'
2018-12-19 20:22:04,965 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 93, in __init__
    options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/nodeStrategies.py", line 152, in respond
    response = self._handleArgs(user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/nodeStrategies.py", line 92, in handleArgs
    matched_child, match, rate, is_aliased = self.match(guess, **kwargs)
AttributeError: 'HandleArgs' object has no attribute 'match'
2018-12-19 20:23:37,138 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 93, in __init__
    options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/nodeStrategies.py", line 153, in respond
    response = self._handleArgs(user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/nodeStrategies.py", line 94, in handleArgs
    logger.debug(f'name: {self.name}, '
AttributeError: 'HandleArgs' object has no attribute 'name'
2018-12-19 20:28:44,321 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 93, in __init__
    options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/nodeStrategies.py", line 157, in respond
    else:
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/nodeStrategies.py", line 94, in handleArgs
    logger.debug(f'name: {self.name}, '
AttributeError: 'HandleArgs' object has no attribute 'name'
2018-12-19 20:35:38,273 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 76, in _handle
    handler = Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 93, in __init__
    options=options)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/nodeStrategies.py", line 152, in respond
    response = self._handleArgs(user_args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/nodeStrategies.py", line 94, in handleArgs
    if rate < self.conf.min_match_percent:
AttributeError: 'HandleArgs' object has no attribute 'conf'
2018-12-19 20:42:10,701 | ERROR | framedata-bot.__main__ | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 56, in on_message
    await self._handle(message)
  File "/home/pete/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 77, in _handle
    await handler.query()
  File "/home/pete/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 98, in query
    channel = await self._getChannel(self._behaviors.send_dm)
AttributeError: 'function' object has no attribute 'send_dm'
2018-12-19 21:02:40,533 | ERROR | framedata-bot.client.py | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 54, in on_message
    await self._handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 74, in _handle
    handler_inst = handler.Handler(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/handler.py", line 28, in __init__
    self._output, self._asyncBehaviour = response
AttributeError: 'Handler' object has no attribute '_asyncBehaviour'
2018-12-20 10:41:45,854 | ERROR | framedata-bot.client.py | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 54, in on_message
    await handler.handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/handler.py", line 28, in handle
    output, asyncBehaviour = _query(msg_obj)
TypeError: cannot unpack non-iterable coroutine object
2018-12-20 10:46:03,873 | ERROR | framedata-bot.client.py | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 54, in on_message
    await handler.handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/handler.py", line 28, in handle
    output, execAsyncBehaviour = await _query(msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/handler.py", line 37, in _query
    response = _active_tree.respond(user_args, msg_obj=msg_obj,
AttributeError: 'ActiveTree' object has no attribute 'respond'
2018-12-20 10:52:08,521 | ERROR | framedata-bot./home/pete/Code/Discord-Bots/melee-frame-data-bot/bot/client.py | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 54, in on_message
    await handler.handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/handler.py", line 30, in handle
    await execAsyncBehaviour()
TypeError: object NoneType can't be used in 'await' expression
2018-12-20 11:08:56,782 | ERROR | framedata-bot.client.py | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 54, in on_message
    await handler.handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/handler.py", line 30, in handle
    await execAsyncBehaviour()
TypeError: object NoneType can't be used in 'await' expression
2018-12-20 11:20:29,877 | ERROR | framedata-bot.client.py | Exception:
Traceback (most recent call last):
  File "/home/pete/.local/share/virtualenvs/melee-frame-data-bot-xbFLIMrz/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/client.py", line 54, in on_message
    await handler.handle(message)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/handler.py", line 31, in handle
    await _send(output, msg_obj)
  File "/home/pete/Dropbox/Code/Discord-Bots/melee-frame-data-bot/bot/handler.py", line 65, in _send
    await channel.send(**out)
AttributeError: 'Message' object has no attribute 'send'
